# Source: apisix/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: apisix
  labels:
    helm.sh/chart: apisix-0.11.0
    app.kubernetes.io/name: apisix
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/version: "2.15.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apisix
      app.kubernetes.io/instance: apisix
  template:
    metadata:
      annotations:
        checksum/config: 8c153a44550ecd96dd60feb8eef52d5ba2e42a11be5f2d1b77ed2fe467cefba7
      labels:
        app.kubernetes.io/name: apisix
        app.kubernetes.io/instance: apisix
    spec:
      securityContext:
        null
      containers:
        - name: apisix
          securityContext:
            null
          image: "apache/apisix:2.15.0-alpine"
          imagePullPolicy: IfNotPresent
          env:
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
            - name: tls
              containerPort: 9443
              protocol: TCP
            - name: admin
              containerPort: 9180
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9080
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - "sleep 30"
          volumeMounts:
            - mountPath: /usr/local/apisix/conf/config.yaml
              name: apisix-config
              subPath: config.yaml
            - mountPath: /usr/local/apisix/logs
              name: log
            - mountPath: /etc/localtime
              name: localtime
          resources:
            {}
      initContainers:
      - name: wait-etcd
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z apisix-etcd.apisix.svc.cluster.local 2379; do echo waiting for etcd `date`; sleep 2; done;"]
      volumes:
        - configMap:
            name: apisix
          name: apisix-config
        - hostPath:
            path: /data/apisix/log
            type: DirectoryOrCreate
          name: log
        - hostPath:
            path: /etc/localtime
          name: localtime          
      affinity:

